name = "Mc 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a882f1ffae38c4829aacca5bb815e7e993057b3ea698466d304a9308620dd9d2"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
