name = "Mc 1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1d610ece8f0d3b4d3834ae4b8fd5854fe2fce1cb131017d311497b6aec11e79"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
